
name: Pull Request Auto Reviwer

on: pull_request


jobs:
    auto_approver:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git Repo.
              uses: actions/checkout@v2
            - name: Collect dir_names under the root dir.
              id: make_dirs_array
              run: |
                dir_list=( `find . -maxdepth 1 -type d | grep -xv '.' | sed -e 's/\.\///' | tr "\n" " "` )
                echo "::set-output name=dir_list::$dir_list"
            - run: git fetch origin ${{ github.base_ref }} --depth=1
            - name: Collect updated dir_names 
              id: make_updated_dirs_array
              run: |
                update_list=(\
                  `git diff --name-only origin/${{ github.base_ref }} HEAD -- . | \
                  sed -e 's/\/.*//' | sort | uniq | tr "\n" " "` \
                )
                update_dirs=(\
                  `printf '%s\n' $update_list ${{ steps.make_dirs_array.outputs.dir_list }} | \
                  | sort | uniq | tr "\n" " "` \
                )
                echo "::set-output name=update_dirs_list::$update_dirs"
            - name: Check authors name
              id: check_author
              run: |
                check_status=0
                pr_thrower=${{github.event.pull_request.user.name}}
                update_dirs=${{steps.make_updated_dirs_array.outputs.update_dirs_list}}
                for dir in update_dirs[@]
                  do
                    name_list=$( \
                      git shortlog -s $dir | awk -F'\t' '{print $2}' \
                    )
                    if printf '%s\n $name_list | grep -qx $pr_thrower; then
                      :
                    else
                      $check_status=1
                    fi
                  done
                
                

