
name: Pull Request Auto Reviwer

on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review

jobs:
    auto_approver:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git Repo.
              uses: actions/checkout@v2
            - run: git fetch origin ${{ github.base_ref }} --depth=1
            - name: Collect updated dir_names 
              id: make_updated_dirs_array
              run: |
                update_list=(\
                  `git diff --name-only origin/${{ github.base_ref }} HEAD -- . | \
                  sed -e 's/\/.*//' | sort | uniq | tr "\n" " "` \
                )
                echo "::set-output name=update_list::$update_list"
            - name: Check authors name
              id: check_author
              run: |
                check_status=0
                pr_thrower=$(\
                  curl https://api.github.com/users/${{github.event.pull_request.user.login}} | \
                  jq -r '.name' \
                )
                updates=${{steps.make_updated_dirs_array.outputs.update_list}}
                for dir in updates[@]
                  do
                    name_list=$( \
                      git shortlog -s $dir | awk -F'\t' '{print $2}' \
                    )
                    if printf '%s\n' $name_list | grep -qx "$pr_thrower"; then
                      :
                    else
                      check_status=1
                    fi
                  done
                echo "::set-output name=check_status::$check_status"
            - name: Auto Approve
              if: ${{steps.check_author.outputs.check_status == 0}}
              uses: hmarr/auto-approve-action@v3
